services:
    frontend: # with the CD pipeline only upload the build folder to the server
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "frontend-prod"
        image: weighttracker/frontend:1.0.0
        restart: always
        ports:
            - 8080:8080
        environment:
            NODE_ENV: production
# TODO: change image and containers names to acoid conflicts with diffrent projects
