services:
     frontend: # https://docs.docker.com/compose/how-tos/file-watch/
          build:
               context: .
               dockerfile: Dockerfile.dev
          container_name: "frontend-dev"
          image: weighttracker/frontend:dev
          ports:
               - 5173:5173
          develop:
               watch:
                  - action: sync
                    path: .
                    target: /app
          environment:
               NODE_ENV: development
               VITE_BACKEND_URL: "http://localhost:3000/api"
          env_file:
               - .env
