# https://docs.docker.com/guides/reactjs/develop/

ARG NODE_VERSION=22.13.1

FROM node:${NODE_VERSION}-alpine AS dev

WORKDIR /app

COPY package*.json ./

RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]
