services:
    backend: # remeber to run migrations from the CD pipeline before starting the production container
        build:
            context: .
            dockerfile: Dockerfile
        container_name: 'backend-prod'
        image: weighttracker/backend:1.0.0
        restart: always
        ports:
            - 3000:3000
        environment:
            NODE_ENV: production
            # DATABASE_URL: 'postgresql://myuser:mypassword@db:5432/mydatabase'
