ARG NODE_VERSION=22.13.1

FROM node:${NODE_VERSION}-alpine AS dev

WORKDIR /app

COPY package*.json ./

RUN npm install

# Prisma needs the schema at build and runtime
COPY prisma ./prisma
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]

