services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: reverse-proxy
        image: weighttracker/nginx:1.0.0
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - frontend
            - backend
